CREATE DATABASE auth_db;
CREATE DATABASE catalog_db;
CREATE DATABASE cart_db;
CREATE DATABASE order_db;
CREATE DATABASE payment_db;

GRANT ALL PRIVILEGES ON DATABASE auth_db TO ecommerce;
GRANT ALL PRIVILEGES ON DATABASE catalog_db TO ecommerce;
GRANT ALL PRIVILEGES ON DATABASE cart_db TO ecommerce;
GRANT ALL PRIVILEGES ON DATABASE order_db TO ecommerce;
GRANT ALL PRIVILEGES ON DATABASE payment_db TO ecommerce;
