apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecommerce.name" . }}-secrets
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.jwtSecret | quote }}
  DB_USER: {{ .Values.postgres.user | quote }}
  DB_PASSWORD: {{ .Values.postgres.password | quote }}
